import { useCallback, useEffect, useState } from "react";
import { ApiError, type Project, request } from "./api";

type Focus = { id: string; project_id: string | null; task_id: string | null; objective: string; duration_minutes: number; started_at: string; ends_at: string; ended_at: string | null; status: string };
const explain = (error: unknown) => error instanceof ApiError ? error.message : "Focus sessions could not be loaded.";

export function FocusSessions({ projects }: { projects: Project[] }) {
  const [sessions, setSessions] = useState<Focus[]>([]); const [objective, setObjective] = useState(""); const [projectId, setProjectId] = useState(""); const [duration, setDuration] = useState(25); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = useCallback(async () => setSessions(await request<Focus[]>("/focus-sessions")), []);
  useEffect(() => { void refresh().catch(cause => setError(explain(cause))); }, [refresh]);
  const active = sessions.find(item => item.status === "active" || item.status === "paused");
  const start = async () => { if (!objective.trim()) return; setBusy(true); setError(""); try { await request<Focus>("/focus-sessions", { method: "POST", body: JSON.stringify({ project_id: projectId || null, objective: objective.trim(), duration_minutes: duration }) }); setObjective(""); await refresh(); setMessage("Focus session started."); window.dispatchEvent(new Event("orin:focus-updated")); } catch (cause) { setError(explain(cause)); } finally { setBusy(false); } };
  const act = async (focus: Focus, action: "pause" | "resume" | "complete" | "cancel") => { setError(""); try { await request(`/focus-sessions/${focus.id}`, { method: "PATCH", body: JSON.stringify({ action }) }); await refresh(); setMessage(`Focus session ${action === "cancel" ? "exited" : `${action}d`}.`); window.dispatchEvent(new Event("orin:focus-updated")); } catch (cause) { setError(explain(cause)); } };
  return <section className="settings-section workspace-settings"><div className="section-heading"><div><span className="eyebrow">FOCUSED WORK</span><h2>Focus sessions</h2></div></div><p>Make time for one objective, then review your recent sessions.</p>{error && <p className="api-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
    {active ? <article className="data-row"><div className="data-main"><strong>Current session · {active.status}</strong><p>{active.objective}</p><small>Started {new Date(active.started_at).toLocaleString()} · {active.duration_minutes} minutes</small></div>{active.status === "active" ? <button className="secondary-button" onClick={() => void act(active, "pause")}>Pause</button> : <button className="secondary-button" onClick={() => void act(active, "resume")}>Resume</button>}<button className="primary-button" onClick={() => void act(active, "complete")}>Complete</button><button className="secondary-button" onClick={() => void act(active, "cancel")}>Exit</button></article> : <form className="settings-section" onSubmit={event => { event.preventDefault(); void start(); }}><label>What will you focus on?<input value={objective} onChange={event => setObjective(event.target.value)} maxLength={500} required placeholder="One clear objective" /></label><label>Project, if relevant<select value={projectId} onChange={event => setProjectId(event.target.value)}><option value="">No project</option>{projects.map(project => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label>Duration<select value={duration} onChange={event => setDuration(Number(event.target.value))}>{[25, 50, 60, 90, 120].map(value => <option key={value} value={value}>{value} minutes</option>)}</select></label><button className="primary-button" disabled={busy}>{busy ? "Starting…" : "Start focus session"}</button></form>}
    <h3>Recent sessions</h3>{sessions.length ? <div className="data-list">{sessions.map(item => <article className="data-row" key={item.id}><div className="data-main"><strong>{item.objective}</strong><p>{item.status} · {item.duration_minutes} minutes</p><small>{new Date(item.started_at).toLocaleString()}{item.ended_at ? ` · ended ${new Date(item.ended_at).toLocaleString()}` : ""}{item.project_id ? ` · ${projects.find(project => project.id === item.project_id)?.name ?? "Project"}` : ""}</small></div></article>)}</div> : <p className="inline-empty">No focus sessions yet.</p>}
  </section>;
}
