import { useEffect, useState, type FormEvent } from "react";
import { ApiError, type Project, request } from "./api";

type Memory = { id: string; project_id: string | null; type: string; title: string; content: string; source: string; archived: boolean; updated_at: string };
const explain = (error: unknown) => error instanceof ApiError ? error.message : "Personal memories could not be loaded.";

export function PersonalMemories({ projects }: { projects: Project[] }) {
  const [memories, setMemories] = useState<Memory[]>([]); const [search, setSearch] = useState(""); const [includeArchived, setIncludeArchived] = useState(false);
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [memoryType, setMemoryType] = useState("preference"); const [projectId, setProjectId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState<string | null>(null);
  const refresh = async () => { const params = new URLSearchParams({ search, include_archived: String(includeArchived) }); setMemories(await request<Memory[]>(`/memories?${params}`)); };
  useEffect(() => { void refresh().catch(cause => setError(explain(cause))); }, [search, includeArchived]);
  const save = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { const wasEditing = Boolean(editing); if (editing) await request(`/memories/${editing}`, { method: "PATCH", body: JSON.stringify({ title: title.trim(), content: content.trim() }) }); else await request("/memories", { method: "POST", body: JSON.stringify({ project_id: projectId || null, memory_type: memoryType, title: title.trim(), content: content.trim(), source: "user" }) }); setTitle(""); setContent(""); setEditing(null); await refresh(); setMessage(wasEditing ? "Memory updated." : "Memory saved."); } catch (cause) { setError(explain(cause)); } finally { setBusy(false); } };
  const update = async (memory: Memory, action: "archive" | "delete") => { setError(""); try { if (action === "delete") await request(`/memories/${memory.id}`, { method: "DELETE" }); else await request(`/memories/${memory.id}`, { method: "PATCH", body: JSON.stringify({ archived: !memory.archived }) }); await refresh(); } catch (cause) { setError(explain(cause)); } };
  return <section className="settings-section workspace-settings"><div className="section-heading"><div><span className="eyebrow">PERSONAL CONTEXT</span><h2>Personal memories</h2></div></div><p>Structured facts you chose to keep. Secrets are rejected.</p>{error && <p className="api-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
    <form className="settings-section" onSubmit={save}><label>Memory type<select value={memoryType} onChange={event => setMemoryType(event.target.value)} disabled={Boolean(editing)}>{["preference", "decision", "fact", "commitment", "workflow", "project_context"].map(item => <option key={item}>{item}</option>)}</select></label><label>Project, if relevant<select value={projectId} onChange={event => setProjectId(event.target.value)} disabled={Boolean(editing)}><option value="">Personal memory</option>{projects.map(project => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label>Title<input value={title} onChange={event => setTitle(event.target.value)} maxLength={180} required /></label><label>Memory details<textarea value={content} onChange={event => setContent(event.target.value)} maxLength={5000} required /></label><button className="primary-button" disabled={busy}>{editing ? "Update memory" : "Save memory"}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setTitle(""); setContent(""); }}>Cancel edit</button>}</form>
    <label className="search-field">Search memories<input value={search} onChange={event => setSearch(event.target.value)} /></label><label className="inline-check"><input type="checkbox" checked={includeArchived} onChange={event => setIncludeArchived(event.target.checked)} />Show archived</label>
    {memories.length ? <div className="data-list">{memories.map(memory => <article className="data-row" key={memory.id}><div className="data-main"><strong>{memory.title} · {memory.type}{memory.archived ? " · archived" : ""}</strong><p>{memory.content}</p><small>Source: {memory.source} · Updated {new Date(memory.updated_at).toLocaleString()}</small></div><button className="secondary-button" onClick={() => { setEditing(memory.id); setTitle(memory.title); setContent(memory.content); }}>Edit</button><button className="secondary-button" onClick={() => void update(memory, "archive")}>{memory.archived ? "Restore" : "Archive"}</button><button className="secondary-button" onClick={() => void update(memory, "delete")}>Delete</button></article>)}</div> : <p className="inline-empty">No memories match this filter.</p>}
  </section>;
}
