import { useEffect, useState, type FormEvent } from "react";
import { ApiError, request } from "./api";

const errorText = (error: unknown) => error instanceof ApiError ? error.message : "Could not complete that request. Please try again.";

type Project = { id: string; name: string; description: string | null; objective?: string | null; status: string; created_at: string; updated_at: string };
type Memory = { id: string; type: string; title: string; content: string; source: string; archived: boolean };
type Context = { progress: { completed_tasks: number; total_tasks: number; percentage: number | null }; tasks: Array<{ id: string; title: string; status: string }>; blockers: Array<{ id: string; title: string }>; activity: Array<{ id: string; summary: string; created_at: string }>; knowledge: Memory[]; next_actions: Array<{ id: string; title: string }> };
type Focus = { id: string; project_id: string; objective: string; duration_minutes: number; ends_at: string; status: string };

export function ProjectWorkspace({ projects, onChanged, initialProjectId }: { projects: Project[]; onChanged: (project: Project) => void; initialProjectId?: string | null }) {
  const [selected, setSelected] = useState(""); const [context, setContext] = useState<Context | null>(null);
  const [objective, setObjective] = useState(""); const [status, setStatus] = useState("active");
  const [name, setName] = useState(""); const [memoryTitle, setMemoryTitle] = useState(""); const [memoryContent, setMemoryContent] = useState(""); const [memoryType, setMemoryType] = useState("decision");
  const [focus, setFocus] = useState<Focus | null>(null); const [duration, setDuration] = useState(60); const [focusObjective, setFocusObjective] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const project = projects.find(item => item.id === selected);
  const refresh = async (id: string) => { setBusy(true); setError(""); try { const [data, memories, sessions] = await Promise.all([request<Context>(`/projects/${id}/context`), request<Memory[]>(`/memories?project_id=${id}`), request<Focus[]>("/focus-sessions")]); setContext({ ...data, knowledge: memories }); setFocus(sessions.find(item => item.status === "active" || item.status === "paused") ?? null); const current = projects.find(item => item.id === id); setObjective(current?.objective ?? ""); setStatus(current?.status ?? "active"); setFocusObjective(current?.objective ?? ""); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } };
  useEffect(() => { if (selected) void refresh(selected); }, [selected]);
  useEffect(() => { if (initialProjectId && projects.some(item => item.id === initialProjectId)) setSelected(initialProjectId); }, [initialProjectId, projects]);
  const createProject = async (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; setBusy(true); setError(""); try { const created = await request<Project>("/projects", { method: "POST", body: JSON.stringify({ name: name.trim() }) }); onChanged(created); setName(""); setSelected(created.id); setMessage("Project created."); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } };
  const saveProject = async () => { if (!project) return; setBusy(true); setError(""); try { const updated = await request<Project>(`/projects/${project.id}`, { method: "PATCH", body: JSON.stringify({ objective, status }) }); onChanged(updated); await refresh(updated.id); setMessage("Project updated."); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } };
  const saveMemory = async (event: FormEvent) => { event.preventDefault(); if (!project || !memoryTitle.trim() || !memoryContent.trim()) return; setBusy(true); setError(""); try { await request<Memory>("/memories", { method: "POST", body: JSON.stringify({ project_id: project.id, memory_type: memoryType, title: memoryTitle.trim(), content: memoryContent.trim(), source: "user" }) }); setMemoryTitle(""); setMemoryContent(""); await refresh(project.id); setMessage("Project knowledge saved."); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } };
  const changeMemory = async (memory: Memory, action: "archive" | "delete") => { if (!project) return; setError(""); try { if (action === "delete") await request(`/memories/${memory.id}`, { method: "DELETE" }); else await request(`/memories/${memory.id}`, { method: "PATCH", body: JSON.stringify({ archived: true }) }); await refresh(project.id); } catch (cause) { setError(errorText(cause)); } };
  const startFocus = async () => { if (!project) return; setBusy(true); setError(""); try { const result = await request<Focus>("/focus-sessions", { method: "POST", body: JSON.stringify({ project_id: project.id, objective: focusObjective.trim() || project.objective || `Work on ${project.name}`, duration_minutes: duration }) }); setFocus(result); window.dispatchEvent(new Event("orin:focus-updated")); setMessage("Focus session started."); } catch (cause) { setError(errorText(cause)); } finally { setBusy(false); } };
  const focusAction = async (action: "pause" | "resume" | "complete" | "cancel") => { if (!focus) return; try { const result = await request<Focus>(`/focus-sessions/${focus.id}`, { method: "PATCH", body: JSON.stringify({ action }) }); setFocus(["complete", "cancel"].includes(action) ? null : result); window.dispatchEvent(new Event("orin:focus-updated")); setMessage(`Focus ${action}d.`); } catch (cause) { setError(errorText(cause)); } };

  return <section className="project-workspace" aria-label="Project intelligence">
    <form className="create-form" onSubmit={createProject}><label className="sr-only" htmlFor="project-create">Project name</label><input id="project-create" value={name} onChange={event => setName(event.target.value)} placeholder="Create a project" /><button className="primary-button" disabled={busy || !name.trim()}>Add project</button></form>
    {projects.length > 0 && <label className="project-picker">Project<select aria-label="Select project" value={selected} onChange={event => setSelected(event.target.value)}><option value="">Choose a project</option>{projects.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
    {error && <p className="api-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
    {busy && <p className="loading-state" role="status">Loading project context…</p>}
    {!projects.length && <p className="inline-empty">No projects yet. Create a project to begin collecting its tasks, activity, decisions, and context.</p>}
    {project && !busy && <>
      <header className="project-heading"><span className="eyebrow">PROJECT OVERVIEW</span><h2>{project.name}</h2><p>{project.description || "Project workspace"}</p></header>
      <section className="home-section"><h3>Objective and status</h3><label>Objective<textarea value={objective} maxLength={2000} onChange={event => setObjective(event.target.value)} placeholder="What is this project meant to achieve?" /></label><label>Status<select value={status} onChange={event => setStatus(event.target.value)}>{["planning", "active", "blocked", "paused", "completed", "archived"].map(value => <option key={value} value={value}>{value}</option>)}</select></label><button className="secondary-button" disabled={busy} onClick={() => void saveProject()}>Save project</button></section>
      {context && <>
        <section className="home-section"><h3>Progress</h3><p>{context.progress.total_tasks ? `${context.progress.completed_tasks} of ${context.progress.total_tasks} tasks complete (${context.progress.percentage}%)` : "No tasks yet; progress will appear when tasks are linked to this project."}</p>{context.progress.percentage !== null && <progress max="100" value={context.progress.percentage} aria-label="Project task completion" />}</section>
        <section className="home-section"><h3>Next actions</h3>{context.next_actions.length ? <ul>{context.next_actions.map(task => <li key={task.id}>{task.title}</li>)}</ul> : <p className="inline-empty">No unfinished project tasks.</p>}</section>
        <section className="home-section"><h3>Blockers</h3>{context.blockers.length ? <ul>{context.blockers.map(task => <li key={task.id}>{task.title}</li>)}</ul> : <p className="inline-empty">No current blockers.</p>}</section>
        <section className="home-section"><h3>Recent activity</h3>{context.activity.length ? <ul>{context.activity.map(item => <li key={item.id}>{item.summary} · {new Date(item.created_at).toLocaleString()}</li>)}</ul> : <p className="inline-empty">No project activity yet.</p>}</section>
        <section className="home-section"><h3>Knowledge and decisions</h3>{context.knowledge.length ? <div className="data-list">{context.knowledge.map(item => <article className="data-row" key={item.id}><div className="data-main"><strong>{item.title} · {item.type}</strong><p>{item.content}</p><small>Source: {item.source}</small></div><button className="secondary-button" onClick={() => void changeMemory(item, "archive")}>Archive</button><button className="secondary-button" onClick={() => void changeMemory(item, "delete")}>Delete</button></article>)}</div> : <p className="inline-empty">No saved project knowledge yet.</p>}
          <form className="settings-section" onSubmit={saveMemory}><h4>Save project knowledge</h4><label>Type<select value={memoryType} onChange={event => setMemoryType(event.target.value)}>{["decision", "fact", "commitment", "workflow", "project_context"].map(value => <option key={value}>{value}</option>)}</select></label><label>Title<input value={memoryTitle} onChange={event => setMemoryTitle(event.target.value)} maxLength={180} required /></label><label>Details<textarea value={memoryContent} onChange={event => setMemoryContent(event.target.value)} maxLength={5000} required /></label><button className="primary-button" disabled={busy}>Save memory</button></form>
        </section>
        <section className="home-section"><h3>Focus session</h3>{focus ? <><p>{focus.objective} · {focus.status} · ends {new Date(focus.ends_at).toLocaleTimeString()}</p>{focus.status === "active" ? <button className="secondary-button" onClick={() => void focusAction("pause")}>Pause</button> : <button className="secondary-button" onClick={() => void focusAction("resume")}>Resume</button>}<button className="secondary-button" onClick={() => void focusAction("complete")}>Complete</button><button className="secondary-button" onClick={() => void focusAction("cancel")}>Exit focus</button></> : <><label>Focus objective<input value={focusObjective} onChange={event => setFocusObjective(event.target.value)} placeholder={project.objective || `Work on ${project.name}`} maxLength={500} /></label><label>Duration<select value={duration} onChange={event => setDuration(Number(event.target.value))}><option value={25}>25 minutes</option><option value={60}>1 hour</option><option value={120}>2 hours</option><option value={240}>4 hours</option></select></label><button className="primary-button" disabled={busy} onClick={() => void startFocus()}>Start focus</button></>}</section>
      </>}
    </>}
  </section>;
}
