import { useEffect, useState, type FormEvent } from "react";
import { ApiError, type Project, request } from "./api";
import { defaultPreferences, type UserPreferences } from "./capabilities";

const explain = (error: unknown) => error instanceof ApiError ? error.message : "Could not load workspace settings.";
type Memory = { id: string; project_id: string | null; type: string; title: string; content: string; source: string; archived: boolean; updated_at: string };
type EnvironmentRule = { surface: string; item: string; visibility: string; priority: number; source: string };
const tools = ["home", "projects", "tasks", "activity", "memories", "focus"];

export function WorkspaceSettings({ projects, preferences, onPreferencesChange }: { projects: Project[]; preferences: UserPreferences; onPreferencesChange: (next: UserPreferences) => void }) {
  const [rules, setRules] = useState<EnvironmentRule[]>([]); const [memories, setMemories] = useState<Memory[]>([]); const [search, setSearch] = useState(""); const [includeArchived, setIncludeArchived] = useState(false);
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [memoryType, setMemoryType] = useState("preference"); const [projectId, setProjectId] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const refreshRules = async () => setRules(await request<EnvironmentRule[]>("/environment/preferences"));
  const refreshMemories = async () => { const params = new URLSearchParams({ search, include_archived: String(includeArchived) }); setMemories(await request<Memory[]>(`/memories?${params}`)); };
  useEffect(() => { Promise.all([refreshRules(), refreshMemories()]).catch(cause => setError(explain(cause))); const layoutChanged = () => refreshRules().catch(cause => setError(explain(cause))); window.addEventListener("orin:workspace-preferences-changed", layoutChanged); return () => window.removeEventListener("orin:workspace-preferences-changed", layoutChanged); }, []);
  useEffect(() => { const timer = window.setTimeout(() => refreshMemories().catch(cause => setError(explain(cause))), 180); return () => window.clearTimeout(timer); }, [search, includeArchived]);
  const visibility = (item: string) => rules.find(rule => rule.surface === "navigation" && rule.item === item)?.visibility ?? (preferences.visibleCapabilities.includes(item as UserPreferences["visibleCapabilities"][number]) ? preferences.pinnedCapabilities.includes(item as UserPreferences["pinnedCapabilities"][number]) ? "prioritized" : "visible" : "hidden");
  const setVisibility = async (item: string, value: string) => { setError(""); try { await request("/environment/preferences", { method: "PUT", body: JSON.stringify({ surface: "navigation", item, visibility: value, priority: value === "prioritized" ? 10 : 0 }) }); const visibleCapabilities = value === "hidden" ? preferences.visibleCapabilities.filter(code => code !== item) : [...new Set([...preferences.visibleCapabilities, item as UserPreferences["visibleCapabilities"][number]])]; const pinnedCapabilities = value === "prioritized" ? [...new Set([...preferences.pinnedCapabilities, item as UserPreferences["pinnedCapabilities"][number]])] : preferences.pinnedCapabilities.filter(code => code !== item); const minimizedCapabilities = value === "minimized" ? [...new Set([...preferences.minimizedCapabilities, item as UserPreferences["minimizedCapabilities"][number]])] : preferences.minimizedCapabilities.filter(code => code !== item); onPreferencesChange({ ...preferences, visibleCapabilities, hiddenCapabilities: preferences.hiddenCapabilities.filter(code => code !== item).concat(value === "hidden" ? [item as UserPreferences["hiddenCapabilities"][number]] : []), pinnedCapabilities, minimizedCapabilities }); await refreshRules(); setMessage("Workspace layout saved. Hidden tools remain available here."); } catch (cause) { setError(explain(cause)); } };
  const reset = async () => { setBusy(true); setError(""); try { await request("/environment/preferences", { method: "DELETE" }); onPreferencesChange(defaultPreferences); await refreshRules(); setMessage("Personalization reset."); } catch (cause) { setError(explain(cause)); } finally { setBusy(false); } };
  const create = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { if (editing) await request(`/memories/${editing}`, { method: "PATCH", body: JSON.stringify({ title: title.trim(), content: content.trim() }) }); else await request("/memories", { method: "POST", body: JSON.stringify({ project_id: projectId || null, memory_type: memoryType, title: title.trim(), content: content.trim(), source: "user" }) }); setTitle(""); setContent(""); setEditing(null); await refreshMemories(); setMessage(editing ? "Memory updated." : "Memory saved."); } catch (cause) { setError(explain(cause)); } finally { setBusy(false); } };
  const archive = async (memory: Memory) => { try { await request(`/memories/${memory.id}`, { method: "PATCH", body: JSON.stringify({ archived: !memory.archived }) }); await refreshMemories(); } catch (cause) { setError(explain(cause)); } };
  const remove = async (memory: Memory) => { try { await request(`/memories/${memory.id}`, { method: "DELETE" }); await refreshMemories(); } catch (cause) { setError(explain(cause)); } };
  return <section className="settings-section workspace-settings"><div className="section-heading"><div><span className="eyebrow">PERSONALIZATION</span><h2>Shape your environment</h2></div></div>
    {error && <p className="api-error" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
    <div className="preference-controls">{tools.map(item => <label key={item}>{item}<select value={visibility(item)} onChange={event => void setVisibility(item, event.target.value)}><option value="visible">Visible</option><option value="prioritized">Prioritized</option><option value="minimized">Minimized</option><option value="hidden">Hidden</option></select></label>)}</div>
    <button className="secondary-button" disabled={busy} onClick={() => void reset()}>Reset layout</button>
    <h3>Memory</h3><p>Structured facts you chose to keep. Secrets are rejected.</p>
    <form className="settings-section" onSubmit={create}><label>Memory type<select value={memoryType} onChange={event => setMemoryType(event.target.value)} disabled={Boolean(editing)}>{["preference", "decision", "fact", "commitment", "workflow", "project_context"].map(item => <option key={item}>{item}</option>)}</select></label><label>Project, if relevant<select value={projectId} onChange={event => setProjectId(event.target.value)} disabled={Boolean(editing)}><option value="">Personal memory</option>{projects.map(project => <option value={project.id} key={project.id}>{project.name}</option>)}</select></label><label>Title<input value={title} onChange={event => setTitle(event.target.value)} maxLength={180} required /></label><label>Memory details<textarea value={content} onChange={event => setContent(event.target.value)} maxLength={5000} required /></label><button className="primary-button" disabled={busy}>{editing ? "Update memory" : "Save memory"}</button>{editing && <button type="button" className="secondary-button" onClick={() => { setEditing(null); setTitle(""); setContent(""); }}>Cancel edit</button>}</form>
    <label className="search-field">Search memories<input value={search} onChange={event => setSearch(event.target.value)} /></label><label className="inline-check"><input type="checkbox" checked={includeArchived} onChange={event => setIncludeArchived(event.target.checked)} />Show archived</label>
    {memories.length ? <div className="data-list">{memories.map(memory => <article className="data-row" key={memory.id}><div className="data-main"><strong>{memory.title} · {memory.type}{memory.archived ? " · archived" : ""}</strong><p>{memory.content}</p><small>Source: {memory.source} · Updated {new Date(memory.updated_at).toLocaleString()}</small></div><button className="secondary-button" onClick={() => { setEditing(memory.id); setTitle(memory.title); setContent(memory.content); }}>Edit</button><button className="secondary-button" onClick={() => void archive(memory)}>{memory.archived ? "Restore" : "Archive"}</button><button className="secondary-button" onClick={() => void remove(memory)}>Delete</button></article>)}</div> : <p className="inline-empty">No memories match this filter.</p>}
  </section>;
}

export function FocusEnvironment() {
  const [focus, setFocus] = useState<{ id: string; objective: string; status: string; ends_at: string } | null>(null);
  const [now, setNow] = useState(Date.now());
  const refresh = async () => { try { const sessions = await request<Array<{ id: string; objective: string; status: string; ends_at: string }>>("/focus-sessions"); setFocus(sessions.find(item => item.status === "active" || item.status === "paused") ?? null); } catch { setFocus(null); } };
  useEffect(() => { void refresh(); const clock = window.setInterval(() => setNow(Date.now()), 1_000); const sync = window.setInterval(() => void refresh(), 30_000); window.addEventListener("orin:focus-updated", refresh); return () => { window.clearInterval(clock); window.clearInterval(sync); window.removeEventListener("orin:focus-updated", refresh); }; }, []);
  if (!focus) return null;
  const action = async (value: "pause" | "resume" | "complete" | "cancel") => { try { await request(`/focus-sessions/${focus.id}`, { method: "PATCH", body: JSON.stringify({ action: value }) }); await refresh(); } catch { /* The project page exposes the API error on refresh. */ } };
  const remaining = Math.max(0, Math.ceil((new Date(focus.ends_at).getTime() - now) / 60_000));
  return <section className="focus-environment" aria-label="Active focus session"><strong>Focus · {focus.status}</strong><span>{focus.objective}</span>{focus.status === "active" && <time dateTime={focus.ends_at}>{remaining ? `${Math.floor(remaining / 60)}h ${remaining % 60}m remaining` : "Session ending"}</time>}<div>{focus.status === "active" ? <button className="secondary-button" onClick={() => void action("pause")}>Pause</button> : <button className="secondary-button" onClick={() => void action("resume")}>Resume</button>}<button className="secondary-button" onClick={() => void action("cancel")}>Exit focus</button></div></section>;
}
