"""core domain schema

Revision ID: fc332f711fcc
Revises: 0001_initial
Create Date: 2026-10-08 01:32:00.041877
"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'fc332f711fcc'
down_revision = '0001_initial'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.bulk_insert(
        sa.table(
            'capabilities',
            sa.column('id', sa.Uuid()),
            sa.column('code', sa.String()),
            sa.column('name', sa.String()),
            sa.column('description', sa.String()),
            sa.column('is_enabled', sa.Boolean()),
        ),
        [
            {'id': uuid.UUID('00000000-0000-0000-0000-000000000001'), 'code': 'home', 'name': 'Home', 'description': 'Your current priorities', 'is_enabled': True},
            {'id': uuid.UUID('00000000-0000-0000-0000-000000000002'), 'code': 'projects', 'name': 'Projects', 'description': 'Organize work by outcome', 'is_enabled': True},
            {'id': uuid.UUID('00000000-0000-0000-0000-000000000003'), 'code': 'tasks', 'name': 'Tasks', 'description': 'Keep track of next steps', 'is_enabled': True},
            {'id': uuid.UUID('00000000-0000-0000-0000-000000000004'), 'code': 'activity', 'name': 'Activity', 'description': 'A record of recent changes', 'is_enabled': True},
            {'id': uuid.UUID('00000000-0000-0000-0000-000000000005'), 'code': 'settings', 'name': 'Settings', 'description': 'Shape your Orin workspace', 'is_enabled': True},
        ],
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'archived', name='project_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_projects_name_nonempty'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_owner_status_updated', 'projects', ['owner_id', 'status', 'updated_at'], unique=False)
    op.create_table('user_capabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=False),
    sa.Column('granted', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pinned = false OR visible = true', name='ck_user_capability_pinned_visible'),
    sa.CheckConstraint('visible = false OR granted = true', name='ck_user_capability_visible_granted'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'capability_id', name='uq_user_capability')
    )
    op.create_index('ix_user_capabilities_user_visible', 'user_capabilities', ['user_id', 'visible'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('density', sa.Enum('comfortable', 'compact', name='density'), server_default='comfortable', nullable=False),
    sa.Column('theme', sa.Enum('light', 'dark', 'system', name='theme'), server_default='light', nullable=False),
    sa.Column('locale', sa.String(length=20), server_default='en', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_preferences_user_id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='project_role'), server_default='viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'blocked', 'done', 'cancelled', name='task_status'), server_default='todo', nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='task_priority'), server_default='normal', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_tasks_title_nonempty'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assignee_status', 'tasks', ['assignee_id', 'status'], unique=False)
    op.create_index('ix_tasks_owner_status_due', 'tasks', ['owner_id', 'status', 'due_at'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_table('activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', sa.Enum('project_created', 'project_updated', 'task_created', 'task_updated', name='activity_type'), nullable=False),
    sa.Column('summary', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_project_created', 'activity', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_activity_task_created', 'activity', ['task_id', 'created_at'], unique=False)
    op.create_index('ix_activity_user_created', 'activity', ['user_id', 'created_at'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'awaiting_approval', 'completed', 'cancelled', 'failed', name='command_status'), server_default='submitted', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_commands_user_created', 'commands', ['user_id', 'created_at'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_task_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name='ck_task_dependency_not_self'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_task_dependency')
    )
    op.create_index('ix_task_dependencies_depends_on', 'task_dependencies', ['depends_on_task_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='execution_status'), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_status_created', 'executions', ['status', 'created_at'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=True),
    sa.Column('execution_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=False),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='approval_status'), server_default='pending', nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(command_id IS NOT NULL AND execution_id IS NULL) OR (command_id IS NULL AND execution_id IS NOT NULL)', name='ck_approval_exactly_one_subject'),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approvals_status_created', 'approvals', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approvals_status_created', table_name='approvals')
    op.drop_table('approvals')
    op.drop_index('ix_executions_status_created', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_task_dependencies_depends_on', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('ix_commands_user_created', table_name='commands')
    op.drop_table('commands')
    op.drop_index('ix_activity_user_created', table_name='activity')
    op.drop_index('ix_activity_task_created', table_name='activity')
    op.drop_index('ix_activity_project_created', table_name='activity')
    op.drop_table('activity')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index('ix_tasks_owner_status_due', table_name='tasks')
    op.drop_index('ix_tasks_assignee_status', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('project_members')
    op.drop_table('user_preferences')
    op.drop_index('ix_user_capabilities_user_visible', table_name='user_capabilities')
    op.drop_table('user_capabilities')
    op.drop_index('ix_projects_owner_status_updated', table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('capabilities')
    for enum_name, enum_values in (
        ('approval_status', ['pending', 'approved', 'rejected', 'cancelled']),
        ('execution_status', ['queued', 'running', 'succeeded', 'failed', 'cancelled']),
        ('command_status', ['submitted', 'awaiting_approval', 'completed', 'cancelled', 'failed']),
        ('activity_type', ['project_created', 'project_updated', 'task_created', 'task_updated']),
        ('task_priority', ['low', 'normal', 'high', 'urgent']),
        ('task_status', ['todo', 'in_progress', 'blocked', 'done', 'cancelled']),
        ('project_role', ['owner', 'editor', 'viewer']),
        ('project_status', ['active', 'paused', 'completed', 'archived']),
        ('theme', ['light', 'dark', 'system']),
        ('density', ['comfortable', 'compact']),
    ):
        postgresql.ENUM(*enum_values, name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
